### ISSUE TITLE
SUPER LONG DEPOSIT TIME TO TRADEORGE

### ISSUE THREAD

**Issue by ssimm1958** [PirateNetwork/pirate#43]
takes bout 4 or 5 hours for a deposit to post to tradeorge

**Comment by Esteban6121** [comment]
I sent a deposit from Lite Wallet to Trade Ogre 24 hrs ago and it still hasn't arrived. Is there any admin here that can advise?

**Comment by Laksh515** [comment]
Sent ARRR to TO around 48 hours ago, 2500 confirmations, TO wallet online now and still not turned up. TO notice says this -->

Warning: Pirate Chain wallet software is unable to cope with demands of exchange, because of these inefficiencies your deposit will take several hours to process and appear. Submit an issue to Pirate developers for faster load times.

Is this being worked on?

What will happen to tx will it go through eventually, be lost or revert at some point?

**Comment by xKOSIUSx** [comment]
Transaction has already went through, TO just needs to credit it to your account.

**Comment by Laksh515** [comment]
Thanks Kossius, can you say whats going on there? a few hours ok but 2 days?

**Comment by xKOSIUSx** [comment]
Idk, DM him on Twitter and ask

**Comment by TeunVanSambeek** [comment]
> Idk, DM him on Twitter and ask

Thanks for your info xKosiusx. Same here. But: Who is him? And is there another way besides Twitter?
